### ISSUE TITLE
asking for a favor

### ISSUE THREAD

**Issue by EndrosG** [Amazinite/ES-Unfettered-Conquest#2]
Hey @Amazinite ,
can you do me a "small" favor?

I created a CT-75 Large Barge in GIMP, but it is ugly. My problem is the upper wing.
Ideally, I would like to have it shortened to the original length. Making in look naturally. But for that the original Star Barge sprite does not have enough pixels "without that wing" to be copied over the current wing.
Alternatively, having a large (or two consecutive wings, as in my pic) requires a different shadow, which I dont get properly done with GIMP easily either.
I cant copy those sections from the (large) Freighter, because it is much brighter there.

![large barge](https://cloud.githubusercontent.com/assets/26883037/24907337/08a067d6-1ebc-11e7-81db-86b27f356289.png)

Since you prooved your blender skills, would you eventually create me a Star Barge with 3 container rows?
Obviously, a 1x and a 2x sprite would be cool.

Btw.: I wonder why the Freighter has only 150 tons of cargo space, using 7 container rows. The Star Barge containers, which are exactly the same, offer 25 tons each. So I assume - and probably will write some lore / mission - that the Syndicate Freighter has a "locked" container cluster used by Syndicate Corp. exclusively. One of their "big powers".

**Comment by EndrosG** [comment]
Did it now :-)
![large barge ct-75](https://cloud.githubusercontent.com/assets/26883037/25312367/93d4444e-2817-11e7-9eb4-413e20e4aad7.png)

But only after I spent the last two days to rework my existing ship sprites from last year and from march.

The hand drawn from last year stayed hand drawn, but I draw them new (I didnt have them as layered images, so I had to draw them from the scratch :-/)
The ship class from march made it into blender.

About the cube 255 remake: the original image (8th may 2016) is the lower left one, the one I finally took is the upper left one.
About the ship class from march: I am very happy with the result (including the size compared to other ships) and even created another new ship for that series. The one which does not have a hand drawn source (center bottom).

![cube_255_remake_tactical_comparison](https://cloud.githubusercontent.com/assets/26883037/25312403/501dbf5e-2818-11e7-9c6e-114adfb2fd56.png)
![mafr_courier_class_remake_comparison](https://cloud.githubusercontent.com/assets/26883037/25312419/9c2f0830-2818-11e7-8648-28ffe46dc7b8.png)

**Comment by EndrosG** [comment]
Hey @Amazinite : may I ask you for a new favor? (well, you didnt fulfill the first anyways, lol).
Could you give me some feedback / review on the Marsian CS ship class images [in my repo](https://github.com/EndrosG/ES-Plugins/tree/master/Marsian%20Ancestors/images/ship)?
I think some of them seem to lack a few details while others look a bit better. But I am not sure.
They do not feature any colors by intention right now.

**Comment by Amazinite** [comment]
Yeah, sorry about the first favor. You had posted that right as I was going out on a vacation, and I just never got back around to it. 

I'll check your repo out in a bit once I get home.

**Comment by Amazinite** [comment]
The **Courier** and **Courier Cargo** look nice as is. Maybe just a little something around the neck area that connects the engines to the cockpit

The **Bulk** seems rather cluttered with this large windmill thing on its top; I think it might do well to decrease the size of it. The texturing on the windmill thing looks amazing though .

The **Courier Catamaran** looks pretty awkward to me. I understand using the same design for different ships, but the Catamaran being nothing more than a single engine with two Courier Cargo cockpits on either side doesn't look good to me. Although, it might just be the fact of the double cockpit thing on either side, because the **Courier Freighter** looks good to me.

Not sure how I feel about the **Courier Cruiseliner**.

I like how the **Courier Racer** looks, as well as the **CS Hamlet** (the latter of which looking fittingly alien like). Although, the Hamlet could probably do with a little more texturing as to not seem so flat around the center. The **CS Village** might need a similar treatment as well.

The **CS Town** looks awesome as is.

The **CS City**, **Large City** (just a heads up, the Large City and Large City@2x look slightly different from eachother, It seems that you didn't update one of them), and **Metropalis Segments vA and vB** (not sure if it's just my monitor, but there seems to be a VERY light difference between the lighting in the normal and @2x versions of these two ships; the @2x versions appear very slightly darker), all seem very, very flat and unappealing to me. I'm not sure what you did with the shadows on these ones, but they seem very shallow and light (or the structures on them are just very tall and therefore the shadows are light so that you can still see the ship). I think it would be better to either add some smaller detail between the structures, lower the strucutres so that dark shadows aren't as obstructive to the ship itself, raise the lightsource so the shadows are smaller but make them darker, or make the shadows dark but add ambient lighting behind the structures so you can still see the details of the ship.

Overall these seem pretty good. I'm just wondering what these cubes are for though. :)

**Comment by EndrosG** [comment]
TYVM.

Did you read the data file too? (yeah, they all have full specifications and descriptions)
Some ugly Syndicate designers created the Catamaran. We all know the Syndicate taste is not the best. It has a bad allocation of turret hardpoints due to this design.
As for the Bulk Freighter: the size of the upper layer is exactly the size of the cargo modules from the Cargo Courier or the Courier Freighter. Just four of these cargo modules.

The Cruiseliner is **the** successor of the Star Queen. 3 cockpit/passenger sections providing a total of 330 bunks (3x 110), with different viewing arcs.

Regarding your comment on the neck / connection between front section and engine section: Yeah, not the masterpiece of arts. But I didnt have a better idea when implementing these in blender. In the picture posted above (in this issue) you can see my original drafts and the result came at least somewhat close.

Regarding the Large City and Metropolis Segment (vA+vB) differences between the 1x and 2x versions: I had to rescale the textures for the 2x versions. I initially had all CS ships half the size, but then the Hamlet (with some 155 bunks as very slow colony ship) was way too small. So I decided to double their size. Problem was then, that the large sprites were too large to fit in my .xcf file so I had to resize all texture layers to double size. And I did not renew the 1x versions afterwards because I thought the regular user wont notice the difference anyways because he uses *either* the 1x or the 2x versions.

Yes, I modified the shadow for the colony ships. Since the buildings on these flat bases are pretty tall (really think of skyscrapers on a flat basement), I did not want to have half of the ship surface being black due to shadow. That was very annoying when I first started with the Metropolis segment (wreckage), that the shadows were so omnipresent and overwhelming.

![marsian cs town blend 3d](https://cloud.githubusercontent.com/assets/26883037/25549532/ae76d172-2c72-11e7-94dc-5051964d8f49.png)

The cubes are the ultimate ships. Though the Metropolis Segment reaches approximately the size of the cube_255 - and the not yet modelled (but well defined) Metropolis, Conurbation and Megalopolis class thus will be larger - the cubes are somewhat a captains dream.
Tons of engine space (yeah, they are fast...), tons of hardpoints (the entire outer structure) and quite a few bays on the tactical versions.

I still have not yet decided whether the cubes will have been designed by the same species or if these cubes belong to their enemies. That plot decision has not yet been made, even though I fly with those cubes since 1 year :-D
Balancing wise they could very well belong to the same species since they share the same technology (in terms of shield matrix, hull material, etc.... "same production line").
I first need to finish rewriting chapter one with all the new modifications I am doing right now. And in order to do so in the way I want, I spent almost the whole day on coding that PR which I made 1-2 hours ago. I really want to make use of that feature.

Sadly, I also would need to finish my Eireen plugin, which still has not received any feedback regarding the two different texturing versions of the Nosy class [ES issue 2411](https://github.com/endless-sky/endless-sky/issues/2411). I need to write more negotiating conversations there. So far I wrote only the first negotiation. Have to do at least two more (Hauler VI series and Nosy class).

**Comment by EndrosG** [comment]
I am almost done with the generation 1 warships. Only have to model the carrier now.
The civil support ships dont have any sprites yet (using the freighter sprite mostly).

![marsian gen 1 heavy warship with 4 drones, 3d scene image](https://github.com/EndrosG/ES-Plugins/blob/master/Marsian%20Ancestors/images/scene/Marsian%20G1%20Heavy%20Warship%20with%204%20Drones%203d%20%28scene%29.png)

**Comment by EndrosG** [comment]
I think I made those ships too big.
Inbetween, I thought they eventually might be too small, but those drones and fighters really dont fit into the scale of regular human ships.
And the carrier now also has twice the width of the Navy Carrier. And the gun ports look awful big, compared to the Navy Carrier.
May be I should just scale them down to 50%. All of the G1 ships.

**Comment by EndrosG** [comment]
I rescaled them down to 50% (that's easier than upscaling, lol) and now they all feel so much better. :)

**Comment by Amazinite** [comment]
We can just talk about this stuff on the Discord now.
